<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\ILP.Shared\ILP.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Config\" />
  </ItemGroup>

</Project>
