//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILP.Shared.InfoExtraction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoExtractionPrompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoExtractionPrompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILP.Shared.InfoExtraction.InfoExtractionPrompts", typeof(InfoExtractionPrompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract accounting header metadata and itemized line items from the document and email.
        ///Rules:
        ///- Output ONLY the two sections demarcated by `[HEADER]` and `[LINE_ITEMS]`.
        ///- No markdown code blocks, backticks, or conversational commentary.
        ///- Use &quot;null&quot; for missing or unreadable values.
        ///- Numbers as plain digits (no &quot;$&quot; or commas). GST rates as decimals (e.g. 0.09, 0.00). Quantities default to 1.00 if unstated.
        ///- Exactly one line per entry (clean line breaks and tabs in text).
        ///
        ///[HEADER]
        ///company-name| Issuing  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractDocumentContent {
            get {
                return ResourceManager.GetString("ExtractDocumentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract accounting header metadata from the document and email into key: value pairs.
        ///Rules: Single line per key. No code blocks, markdown, or commentary. Use &quot;null&quot; if missing/unreadable. Numbers as plain digits (no &quot;$&quot; or commas). Tax rates as decimals (e.g. 0.09).
        ///
        ///Keys &amp; Definitions:
        ///company-name| Issuing supplier name
        ///company-uen| Singapore UEN (e.g. 201234567M)
        ///company-tax-registration-number| GST Reg No (e.g. M90000000X)
        ///document-number| Invoice or reference number
        ///document-type| Exactly one of| Invo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractDocumentHeaderInfo {
            get {
                return ResourceManager.GetString("ExtractDocumentHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all line items from the document table into a pipe-delimited CSV.
        ///Rules: Output header row then data rows only. Exactly one line per item (strip internal newlines/tabs). No markdown blocks or commentary. Use &quot;null&quot; if missing. Numbers as plain digits (no &quot;$&quot; or commas). Quantities default to 1.00 if unstated. Tax rates as decimals (e.g. 0.09, 0.00).
        ///
        ///Columns &amp; Definitions:
        ///sn| Sequential item index (1, 2, ...)
        ///description| Product or service description
        ///quantity| Billed quantity (default 1.00) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractDocumentLineItemInfo {
            get {
                return ResourceManager.GetString("ExtractDocumentLineItemInfo", resourceCulture);
            }
        }
    }
}
